server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sec_test
    username: sickeer
    password: 21062007

auth:
  cookie:
    auth: AUTH-TOKEN
    refresh: REFRESH-TOKEN
    secret: jfdghkdfgw23;riqpow7898234njk
    expiration-auth: 600000
    expiration-refrech: 31536000
    path:
